apiVersion: v2
name: istio-crds
version: 1.25.2-bb.0
appVersion: 1.25.2
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
  - base
  - istio-discovery
sources:
  - https://github.com/istio/istio
dependencies:
  - name: base
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.25.2
    alias: upstream
annotations:
  bigbang.dev/passthrough: "true"
  bigbang.dev/passthrough-toplevel-key: upstream
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Istio: 1.25.2
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find upstream chart's release notes and CHANGELOG here](https://istio.io/latest/news/releases)
